server:
  port: 8080
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://localhost:5432/identityauth
    username: identity_user
    password: identity_user

springdoc:
  packages-to-scan: com.youtube.identityauthservice.interfaces.rest

# Domain Event Publisher Configuration (background service)
outbox:
  domain-event-publisher:
    backend:
      fully-qualified-namespace: output-event.servicebus.windows.net
      queue-name: ${AZURE_SERVICEBUS_QUEUE_NAME:}

logging:
  level:
    com.youtube.identityauthservice: ${LOG_LEVEL:INFO}
